Installing TensorFlow 2.0

In [18]:
#!pip install tensorflow-gpu

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.8.0'

# Constants/Tensors

In [4]:
#Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [5]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

In [6]:
#Getting shape of a tensor
tensor_20.shape

TensorShape([2, 2])

# Getting values from constants

In [7]:
# Getting values from a TensorFlow constant to numpy
tensor_20.numpy()

array([[23,  4],
       [32, 51]])

In [9]:
# convert a numpy matrix  to a TensorFlow tensor
numpy_matrix = np.array([[23,  4], [32, 51]])

In [10]:
tensor_from_numpy = tf.constant(numpy_matrix)

In [11]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

# Operations with constants/tensors

In [12]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

# Addition between scalar and tensor

In [13]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

# Multiplication between scalar and tensor

In [14]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]])>

# Using Numpy functions on TensorFlow tensors

In [15]:
#Squaring all numbers in a tensorflow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [16]:
#Square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

# Dot product between two tensors

In [17]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]])

# Operations with variables

In [19]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

# Getting raw value from the variable

In [20]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

# Changing specific value in the TensorFlow variable

In [21]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [22]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

# Strings in TensorFlow

In [23]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

# Simple string operations

In [24]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [25]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119])>

# Storing arrays of strings

In [26]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [27]:
#iterate through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
